root: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
  - react-hooks
extends:
  - next/core-web-vitals
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
rules:
  curly: error
  no-return-await: error
  prefer-arrow-callback: error
  prettier/prettier:
    - error
    - arrowParens: always
      semi: false
      singleQuote: true
      trailingComma: all
  react/prop-types: off
  react/display-name: off
  require-await: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
  import/order:
    - error
    - newlines-between: always
  import/no-named-as-default: off